# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='content',
        ),
        migrations.DeleteModel(
            name='popular',
        ),
        migrations.RemoveField(
            model_name='top_spots',
            name='image',
        ),
    ]
