# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160227_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='top_spots',
        ),
    ]
